name: 05 - 01 - Event Filters and Activity Types
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a pull request is open or synchronised AND base branch is main"