name: 09 - Using functions
on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: exit 1
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will run if previous step succeed."
      - name: I will be executed
        if: ${{ failure() }}
        run: echo "I will run if previous step fails."
      - name: I will be executed
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when workflow is cancelled."
      - name: I will be executed when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print, only when workflow is cancelled."